### ISSUE TITLE
Sexplib0 changes default exception printing behavior

### ISSUE THREAD

**Issue by bandersongit** [janestreet/sexplib0#1]
Adding a dependency on Base caused a change in the behavior of Printexc.to_string's exception printing, which I traced to the call to Printexc.register_printer in sexp_conv.ml in this repo. 

We had the following snapshot fail as a result:
![image](https://user-images.githubusercontent.com/5252755/55984081-7bc31680-5c51-11e9-832f-5d8a61123f2d.png)

I think that ideally the printing behavior for pervasive exceptions using primitive types would not be changed as a side effect of taking on a dependency on Base (which depends on this).

**Comment by aalekseyev** [comment]
This should be fixed in 05c52b5.
