### ISSUE TITLE
No README / how is this different from sexplib?

### ISSUE THREAD

**Issue by rwmjones** [janestreet/sexplib0#5]
There's no README for this project and there probably should be.

More to the point, what is the relationship between this package and sexplib?  It appears to be a kind of simplified sexplib.  Is it a clean replacement?  Is one aiming to take over eventually from the other?  Or two projects that happen to have similar names but are unrelated?  Which came first (I'm guessing the other one).  This could all be explaining in the README.

**Comment by aalekseyev** [comment]
Added a small readme in 05c52b5. (and yes, I fail at markdown)
